language: node_js
node_js:
- '8'
matrix:
  include:
  - os: linux
    dist: xenial
    sudo: required
  - os: osx
cache:
  yarn: true
notifications:
  email: false
script:
- npm run build
- npm run build:electron
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: 
    - dist/*.deb
    - dist/*.AppImage
  api_key:
    secure: JYXGHpIZaLqBnhl93bs45vbh7nVA7Sot10Zb3jxdJv6NpL8Exg44T5H/4xMa6aQiUX7IlD/t1ba+HljgHt2fiyF5gXBx6bCIoFEyv6KfxkeN3YIhb21rvmWeOWDHJv6oHKLbQnHe5YlTAkBDhi1O05DlJ8DDvd8P35k7TOQwEa3LFC/2veIV0IaYmxv7nd3QUl8Km75RwyktgLQJ3a73lqSuV+hchTJ+MzkZ2LO3zbIRLf2zU5dNV8UrlkNqBMt3IiWasZ64nFx+RVYFIy0nT1yJCkjoGLYhJXd0Ien4BFQBPjXC2h2C8dH4SRKeSvuVi2kyqbWLxuhh0Z1cUw3f7lJDZ7/wqIJavOSXan/6yZtWNqMas6S6i30zwHvvGQn7q8IWfyO7Qt/cOGDISop8bCDcRkPOT70a9FA3Xi9keWjTIDJhv+wLXAwwSwI+rvRJxoCqu0a08YFyW2z0EP99vlp9ireyDrpvTBjCSuL51s+sZXIpbJj4BeC3ohxasMjySJLthvwW894mlTysaza7QqHMMctjkpzUm2Xp4YTzSG0bj870xO85Uyim+nOEPXhm9fD6XLI6lJ8/oNZOA6DPThJ9UFtCfuVm0AwFaW96HcB4hp31DTk6sPEI3XdHhLgX3iUJK4Uuk9TjQWHzgoxlsUnr0gi37tIU2nk5CG5+i50=
  file: dist/*.deb
  on:
    repo: JbIPS/Silex
    branch: electron-ci
env:
  global:
    GH_TOKEN=JYXGHpIZaLqBnhl93bs45vbh7nVA7Sot10Zb3jxdJv6NpL8Exg44T5H/4xMa6aQiUX7IlD/t1ba+HljgHt2fiyF5gXBx6bCIoFEyv6KfxkeN3YIhb21rvmWeOWDHJv6oHKLbQnHe5YlTAkBDhi1O05DlJ8DDvd8P35k7TOQwEa3LFC/2veIV0IaYmxv7nd3QUl8Km75RwyktgLQJ3a73lqSuV+hchTJ+MzkZ2LO3zbIRLf2zU5dNV8UrlkNqBMt3IiWasZ64nFx+RVYFIy0nT1yJCkjoGLYhJXd0Ien4BFQBPjXC2h2C8dH4SRKeSvuVi2kyqbWLxuhh0Z1cUw3f7lJDZ7/wqIJavOSXan/6yZtWNqMas6S6i30zwHvvGQn7q8IWfyO7Qt/cOGDISop8bCDcRkPOT70a9FA3Xi9keWjTIDJhv+wLXAwwSwI+rvRJxoCqu0a08YFyW2z0EP99vlp9ireyDrpvTBjCSuL51s+sZXIpbJj4BeC3ohxasMjySJLthvwW894mlTysaza7QqHMMctjkpzUm2Xp4YTzSG0bj870xO85Uyim+nOEPXhm9fD6XLI6lJ8/oNZOA6DPThJ9UFtCfuVm0AwFaW96HcB4hp31DTk6sPEI3XdHhLgX3iUJK4Uuk9TjQWHzgoxlsUnr0gi37tIU2nk5CG5+i50=

