language: node_js
node_js:
- '8'
matrix:
  include:
  - os: linux
    dist: xenial
    sudo: required
  - os: osx
cache:
  yarn: true
notifications:
  email: false
script:
- npm run build
- npm run build:electron
deploy:
  provider: releases
  api_key:
    secure: P9I2XNABp2WesUl0ubKXfFZOCw/PkN3UFLiKcr0eSIVJjPp5oYPOSpYV6SalG3tr8jBpXY+lepGMbTQYMigVtFhn16Vc48IsuffMzp30CXpOAJKFQFpHEeIDdvOZaxFPHk5+haV/2/C8nbaGu/TG2YHLBAT3WBuGZTVdyT1Rcb07vFm1UgW5lcnZkW73+G6v751SNvmNNayzu55R9AubYdpqiZleuCZi/u9j9gj3XtNTa4F+1KbvlnRybg6q48qhbyXPNuKMsBTCfxH5YqMNLi+LAeEJyZmJDrwlfkNDqUCAh24ODhjYSB+0und+Ao3hWrXP3dQ4oGhboRrXky6T2v7FbXLOMVJLWG8bGyhYEMYJ9zI9VMbIFeNXQEszCiYohUf1NoaDWBXk8ZsLDfmISiSor++Q7AuUag2z3WBONVcyCYBjOaKCQnsIbiONxLvNek7eyO8Lyjcsp4KSlo+frRquPzU7f5Xdwo2jqTh5w0zOIsQbsG0ePHMES21GU5Jqwi3+3LC1mAP4jDkNQLwGStpk3b824S1kOeA+T6slAPwWLQhKqCRxKfagBXWa3XvAmS2TZ20mG98vFK/UTQE9scgdw85Uq3cw7+VYApykk6t7SIQj53HGARV8oljzvSJmH/HknxTV/1+MwEUYqcNNyrciu64rRyOXyb3ydcOrmOo=
  file: dist/*.deb
  on:
    tag: true

